# Generated by Django 3.1.2 on 2020-10-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201006_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
