# Generated by Django 3.1.2 on 2020-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201006_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='reviews',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
